React-Calculator milestone-2
Wusinho/React-Calculator pull request #3
Opened 2021-07-08 22:57 UTC by Wusinho

This project is an App Calculator using React.
## Built with

- HTML
- JavaScript
- Webpack
- Package.json
- React

2021-07-09 06:01 UTC, afanimartin requested changes
## Changes Required 🙏🏿 🙏🏿 🙏🏿 
Nice work in this milestone.
### Highlights 👍🏿 👍🏿 👍🏿 
- Correct implementation of `ButtonPanel` component

### Change(s) 🔕 🔕 🔕 
- Update readme file. Check comments
- Check comments for more suggestions


### Martin Afani
#### Slack: whiz25

2021-07-09 06:01 UTC, afanimartin commented on src/components/App.js
> +    <ButtonPanel />
- You need to also render the `Display` component
- Use `React.Fragment` shorthand syntax: `<>...</>`

2021-07-09 06:01 UTC, afanimartin commented on src/components/Display.jsx
> +const Rectangle = (props) => (<div className="rectangle">{props.value || '0'}</div>);
- Why is the component named `Rectangle`? It's not a clear name. Change it to `Display`

2021-07-09 06:01 UTC, afanimartin commented on src/components/Square.jsx
> +const Square = (props) => (<button className="square" onClick={props.onClick}>{props.value}</button>);
- This name doesn't make sense. It should be `Button`. The component is a button. Make it clear.

2021-07-09 06:01 UTC, afanimartin commented on src/components/Square.jsx
> +/* eslint-disable react/destructuring-assignment */
- Do not disable the linter rules. Learn to fix those errors instead. In this case, the errors can actually be fixed.

2021-07-09 06:01 UTC, afanimartin commented on README.md
> +![screenshot](./src/assets/static/Screenshot.png)
- Update the `To get a local copy of this repo` instruction. Step 1 has this instruction: `$ cd "here comes the path of your selected directory (double quotes must not be here)"`. This instruction is not clear and doesn't look useful to a user who wants to checkout the app locally. Always be very explicit in your instructions.

2021-07-13 05:35 UTC, taiwo2 requested changes
# STATUS: CHANGES REQUIRED ♻️ 
@Wusinho well done for the task, Kindly implement the changes suggested by the previous Code Reviewer:
### Highlights
- [ ] Use React.Fragment shorthand syntax: <>...</> 👍🏻 
#### To Improve
### `App` component
- [ ] it renders the `Display` and `ButtonPanel` components  ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/react_reducx/calculator/milestone2/app/appFunctionalComponent.png))
###  `button` component
- [ ] Do not disable the linter rules. Learn to fix those errors instead. In this case, the errors can actually be fixed in your `button.jsx`
- [ ]   It should be Button. The component is a button. Make it clear.
- [ ]  it accepts `a button name` as an incoming prop ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/react_reducx/calculator/milestone2/button/acceptProp.png))

### Once specific changes make kindly request for another review

2021-07-14 00:21 UTC, NtwaliHeritier approved these changes
### **STATUS: APPROVED👍️👍️👍️👍️**

Hello @Wusinho 
Great work making the requested changes👏️👏️👏️

You can merge👍️👍️

Happy coding💻️💻️

2021-07-14 16:18 UTC, merged